name: Auto-Rebase-PR
author: Timothée Dorand <timothee.dorand@ninox.com>
description: Automatically keep pull requests without auto-merged enabled up to date with their base branch.
inputs:
  github_token:
    description: Token for the GitHub API.
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
branding:
  icon: refresh-cw
  color: blue
